# Generated by Django 6.0.5 on 2026-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meet_link',
            field=models.URLField(blank=True, help_text='Google Meet link for this room', null=True),
        ),
    ]
