# Generated by Django 6.0.5 on 2026-05-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_meet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='meet_link',
        ),
    ]
