# Generated by Django 6.0.5 on 2026-05-13 06:11

from django.db import migrations

def create_topics(apps, schema_editor):
    Topic = apps.get_model('base', 'Topic')

    topics = [
        'Python',
        'Django',
        'AI',
        'Cyber Security',
        'Machine Learning'
    ]

    for topic in topics:
        Topic.objects.get_or_create(name=topic)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_topics),
    ]