# Generated by Django 6.0.5 on 2026-05-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_room_meet_link'),
        ('base', '0007_auto_20260513_0611'),
    ]

    operations = [
    ]
